var keyMirror = require('keyMirror');

module.exports = keyMirror({
	RECEIVE_EVENTEDIT_DATA: null,

	//BASE
	EVENTEDIT_BASE_CHANGE_NAME: null,
	EVENTEDIT_BASE_CHANGE_TYPE: null,
	EVENTEDIT_BASE_CHANGE_CODE: null,
	EVENTEDIT_BASE_CHANGE_START_DATETIME: null,
	EVENTEDIT_BASE_CHANGE_FINISH_DATETIME: null,
	EVENTEDIT_BASE_CHANGE_EDUCATION_ORG: null,
	EVENTEDIT_BASE_CHANGE_EDUCATION_METHOD: null,
	EVENTEDIT_BASE_CHANGE_PLACE: null,

	//REQUESTS
	EVENTEDIT_REQUESTS_CHANGE_IS_DATE_REQUEST_BEFORE_BEGIN: null,
	EVENTEDIT_REQUESTS_CHANGE_REQUEST_BEGIN_DATE: null,
	EVENTEDIT_REQUESTS_CHANGE_REQUEST_OVER_DATE: null,
	EVENTEDIT_REQUESTS_CHANGE_IS_AUTOMATIC_INCLUDE: null,
	EVENTEDIT_REQUESTS_CHANGE_IS_APPROVE_BY_BOSS: null,
	EVENTEDIT_REQUESTS_CHANGE_IS_APPROVE_BY_TUTOR: null,
	EVENTEDIT_REQUESTS_SORT_TABLE: null,
	EVENTEDIT_REQUESTS_CHANGE_STATUS: null,

	//COLLABORATORS
	EVENTEDIT_COLLABORATORS_TOGGLE_IS_ASSIST: null,
	EVENTEDIT_COLLABORATORS_SORT_TABLE: null,
	EVENTEDIT_COLLABORATORS_TOGGLE_CHECKED_ALL: null,
	EVENTEDIT_COLLABORATORS_TOGGLE_CHECKED: null,
	EVENTEDIT_COLLABORATORS_REMOVE_ITEMS: null,
	EVENTEDIT_COLLABORATORS_NOTIFICATE_ITEMS: null,
	EVENTEDIT_COLLABORATORS_UPDATE_ITEMS: null
});