var keyMirror = require('keyMirror');

module.exports = keyMirror({
	RECEIVE_EVENTEDIT_DATA: null,

	//BASE
	CHANGE_EVENTEDIT_NAME: null,
	CHANGE_EVENTEDIT_TYPE: null,
	CHANGE_EVENTEDIT_CODE: null,
	CHANGE_EVENTEDIT_START_DATETIME: null,
	CHANGE_EVENTEDIT_FINISH_DATETIME: null,
	CHANGE_EVENTEDIT_EDUCATION_ORG: null,
	CHANGE_EVENTEDIT_EDUCATION_METHOD: null,
	CHANGE_EVENTEDIT_PLACE: null,

	//REQUESTS
	CHANGE_EVENTEDIT_IS_DATE_REQUEST_BEFORE_BEGIN: null,
	CHANGE_EVENTEDIT_REQUEST_BEGIN_DATE: null,
	CHANGE_EVENTEDIT_REQUEST_OVER_DATE: null,
	CHANGE_EVENTEDIT_IS_AUTOMATIC_INCLUDE_IN_COLLABORATORS: null,
	CHANGE_EVENTEDIT_IS_APPROVE_BY_BOSS: null,
	CHANGE_EVENTEDIT_IS_APPROVE_BY_TUTOR: null
});